/**
 * Canonical sink for knowledge generated by Dream and enrichment phases.
 *
 * The markdown file is the commit point. Database pages, chunks, and embeddings
 * are a derived projection and are never written before the file. A durable
 * receipt beside the source checkout lets a later Dream startup repair the
 * narrow crash window between atomic placement and import.
 */
import {
  closeSync,
  existsSync,
  fsyncSync,
  mkdirSync,
  openSync,
  readFileSync,
  readdirSync,
  renameSync,
  statSync,
  unlinkSync,
  writeFileSync,
} from 'node:fs';
import { createHash, randomBytes } from 'node:crypto';
import { dirname, join, relative, resolve } from 'node:path';
import type { BrainEngine } from './engine.ts';
import { importFromFile } from './import-file.ts';
import { LockUnavailableError, withRefreshingLock, syncLockId } from './db-lock.ts';
import { isWriteTargetContained } from './path-confine.ts';
import { validateSlug, validateSourceId } from './utils.ts';
import { gbrainPath } from './config.ts';

const RECEIPT_VERSION = 1;
const PATH_LEASE_MINUTES = 2;

export type GeneratedOutputStatus = 'projected' | 'noop' | 'file_only' | 'conflict';

export interface GeneratedOutputReceipt {
  version: 1;
  source_id: string;
  slug: string;
  relative_path: string;
  digest: string;
  expected_digest: string | null;
  state: 'pending' | 'file_committed' | 'projected' | 'projection_failed';
  updated_at: string;
  error_code?: 'projection_failed';
}

export interface GeneratedOutputWriteResult {
  status: GeneratedOutputStatus;
  source_id: string;
  slug: string;
  digest: string;
  path: string;
  receipt_path: string;
  error?: string;
}

export interface WriteGeneratedOutputOpts {
  sourceId?: string;
  /**
   * Source checkout used when sources.local_path is not configured. For a
   * non-default source this is that source's own checkout, not a host repo.
   */
  brainDir?: string;
  /**
   * Digest observed before generation began. `null` means the path was absent.
   * A different live digest is an explicit conflict; identical new content
   * still coalesces to a no-op.
   */
  expectedDigest: string | null;
  noEmbed?: boolean;
  /** Test seam / private runtime-state override. */
  receiptDir?: string;
  /** Test-only crash seam. */
  _failAt?: 'before_placement' | 'after_placement' | 'before_import';
}

export interface ReconcileGeneratedOutputOpts {
  sourceId?: string;
  brainDir?: string;
  noEmbed?: boolean;
  /** Test seam / private runtime-state override. */
  receiptDir?: string;
}

export function generatedOutputDigest(content: string): string {
  return createHash('sha256').update(content, 'utf8').digest('hex');
}

export function stampGeneratedMarkdown(content: string): string {
  if (/\n(?:gbrain_generated|dream_generated):\s*true(?:\r?\n|$)/i.test(content)) {
    return content;
  }
  if (content.startsWith('---\n')) {
    return content.replace('---\n', '---\ngbrain_generated: true\ndream_generated: true\n');
  }
  return `---\ngbrain_generated: true\ndream_generated: true\n---\n${content}`;
}

export function readGeneratedOutputDigest(path: string): string | null {
  if (!existsSync(path)) return null;
  return generatedOutputDigest(readFileSync(path, 'utf8'));
}

export async function snapshotGeneratedOutputDigests(
  engine: BrainEngine,
  prefixes: readonly string[],
  opts: Pick<WriteGeneratedOutputOpts, 'sourceId' | 'brainDir'> = {},
): Promise<Record<string, string>> {
  const sourceId = opts.sourceId ?? 'default';
  const root = await resolveSourceRoot(engine, sourceId, opts.brainDir);
  const result: Record<string, string> = {};
  const seenRoots = new Set<string>();
  for (const glob of prefixes) {
    const staticPrefix = glob.split('*', 1)[0].replace(/\/+$/, '');
    const scanRoot = staticPrefix ? join(root, staticPrefix) : root;
    if (seenRoots.has(scanRoot) || !existsSync(scanRoot)) continue;
    seenRoots.add(scanRoot);
    const stack = [scanRoot];
    while (stack.length > 0) {
      const dir = stack.pop()!;
      for (const entry of readdirSync(dir, { withFileTypes: true })) {
        if (entry.name.startsWith('.')) continue;
        const path = join(dir, entry.name);
        if (entry.isDirectory()) stack.push(path);
        else if (entry.isFile() && entry.name.endsWith('.md')) {
          const slug = relative(root, path).replace(/\.md$/, '').split('\\').join('/');
          result[slug] = generatedOutputDigest(readFileSync(path, 'utf8'));
        }
      }
    }
  }
  return result;
}

function receiptName(sourceId: string, slug: string): string {
  return createHash('sha256').update(`${sourceId}\0${slug}`).digest('hex') + '.json';
}

function receiptDirectory(root: string, override?: string): string {
  if (override) return override;
  const sourceRootId = createHash('sha256').update(root).digest('hex').slice(0, 20);
  return gbrainPath('generated-output-receipts', sourceRootId);
}

function atomicWrite(path: string, content: string): void {
  mkdirSync(dirname(path), { recursive: true });
  const tmp = `${path}.tmp.${process.pid}.${randomBytes(4).toString('hex')}`;
  let fd: number | null = null;
  try {
    fd = openSync(tmp, 'w', 0o600);
    writeFileSync(fd, content, 'utf8');
    fsyncSync(fd);
    closeSync(fd);
    fd = null;
    renameSync(tmp, path);
    const dirFd = openSync(dirname(path), 'r');
    try { fsyncSync(dirFd); } finally { closeSync(dirFd); }
  } catch (error) {
    if (fd !== null) {
      try { closeSync(fd); } catch { /* best effort */ }
    }
    try { if (existsSync(tmp)) unlinkSync(tmp); } catch { /* best effort */ }
    throw error;
  }
}

function writeReceipt(path: string, receipt: GeneratedOutputReceipt): void {
  atomicWrite(path, `${JSON.stringify(receipt, null, 2)}\n`);
}

async function withBoundedLockRetry<T>(
  engine: BrainEngine,
  lockId: string,
  work: () => Promise<T>,
): Promise<T> {
  for (let attempt = 0; ; attempt++) {
    try {
      return await withRefreshingLock(engine, lockId, work);
    } catch (error) {
      if (!(error instanceof LockUnavailableError) || attempt >= 40) throw error;
      await new Promise((resolveDelay) => setTimeout(resolveDelay, 5));
    }
  }
}

async function resolveSourceRoot(
  engine: BrainEngine,
  sourceId: string,
  brainDir?: string,
): Promise<string> {
  const rows = await engine.executeRaw<{ local_path: string | null }>(
    'SELECT local_path FROM sources WHERE id = $1',
    [sourceId],
  );
  const configured = rows[0]?.local_path ?? null;
  const candidate = configured ?? brainDir ?? (sourceId === 'default'
    ? await engine.getConfig('sync.repo_path')
    : null);
  if (!candidate) {
    throw new Error(`generated output requires a local checkout for source "${sourceId}"`);
  }
  const root = resolve(candidate);
  if (!existsSync(root) || !statSync(root).isDirectory()) {
    throw new Error(`generated output checkout is unavailable for source "${sourceId}"`);
  }
  return root;
}

export async function resolveGeneratedOutputPath(
  engine: BrainEngine,
  slug: string,
  opts: Pick<WriteGeneratedOutputOpts, 'sourceId' | 'brainDir'> = {},
): Promise<string> {
  const sourceId = opts.sourceId ?? 'default';
  validateSourceId(sourceId);
  const normalizedSlug = validateSlug(slug);
  const root = await resolveSourceRoot(engine, sourceId, opts.brainDir);
  const path = join(root, `${normalizedSlug}.md`);
  if (!isWriteTargetContained(path, root)) {
    throw new Error(`generated output path escapes source root: ${normalizedSlug}`);
  }
  return path;
}

async function projectCanonicalFile(
  engine: BrainEngine,
  filePath: string,
  slug: string,
  sourceId: string,
  digest: string,
  noEmbed: boolean,
): Promise<void> {
  // Recheck after placement and immediately before import. Cooperating sync
  // and generated writers hold the same source lock, so the digest remains
  // stable for the import transaction.
  if (readGeneratedOutputDigest(filePath) !== digest) {
    throw new Error(`generated output digest changed before import: ${sourceId}/${slug}`);
  }
  const imported = await importFromFile(engine, filePath, `${slug}.md`, {
    sourceId,
    noEmbed,
    inferFrontmatter: false,
  });
  if (imported.status === 'error' || imported.status === 'skipped') {
    throw new Error(imported.error ?? `generated output import ${imported.status}`);
  }
}

export async function writeGeneratedOutput(
  engine: BrainEngine,
  slug: string,
  content: string,
  opts: WriteGeneratedOutputOpts,
): Promise<GeneratedOutputWriteResult> {
  const sourceId = opts.sourceId ?? 'default';
  validateSourceId(sourceId);
  const normalizedSlug = validateSlug(slug);
  const root = await resolveSourceRoot(engine, sourceId, opts.brainDir);
  const filePath = join(root, `${normalizedSlug}.md`);
  if (!isWriteTargetContained(filePath, root)) {
    throw new Error(`generated output path escapes source root: ${normalizedSlug}`);
  }
  const digest = generatedOutputDigest(content);
  const receiptPath = join(
    receiptDirectory(root, opts.receiptDir),
    receiptName(sourceId, normalizedSlug),
  );
  const pathLease = `gbrain-generated:${createHash('sha256')
    .update(`${sourceId}\0${filePath}`)
    .digest('hex')
    .slice(0, 32)}`;

  return withBoundedLockRetry(engine, syncLockId(sourceId), () =>
    withRefreshingLock(engine, pathLease, async () => {
      const currentDigest = readGeneratedOutputDigest(filePath);
      const base: Omit<GeneratedOutputReceipt, 'state' | 'updated_at'> = {
        version: RECEIPT_VERSION,
        source_id: sourceId,
        slug: normalizedSlug,
        relative_path: relative(root, filePath),
        digest,
        expected_digest: opts.expectedDigest,
      };

      if (currentDigest !== digest && currentDigest !== opts.expectedDigest) {
        return {
          status: 'conflict',
          source_id: sourceId,
          slug: normalizedSlug,
          digest,
          path: filePath,
          receipt_path: receiptPath,
          error: `expected digest ${opts.expectedDigest ?? '<absent>'}, found ${currentDigest ?? '<absent>'}`,
        };
      }

      let priorReceipt: GeneratedOutputReceipt | null = null;
      try {
        if (existsSync(receiptPath)) {
          priorReceipt = JSON.parse(readFileSync(receiptPath, 'utf8')) as GeneratedOutputReceipt;
        }
      } catch {
        priorReceipt = null;
      }
      if (currentDigest === digest && priorReceipt?.state === 'projected') {
        return {
          status: 'noop',
          source_id: sourceId,
          slug: normalizedSlug,
          digest,
          path: filePath,
          receipt_path: receiptPath,
        };
      }

      writeReceipt(receiptPath, {
        ...base,
        state: 'pending',
        updated_at: new Date().toISOString(),
      });
      if (opts._failAt === 'before_placement') throw new Error('injected failure before placement');

      if (currentDigest !== digest) atomicWrite(filePath, content);
      if (opts._failAt === 'after_placement') throw new Error('injected failure after placement');

      writeReceipt(receiptPath, {
        ...base,
        state: 'file_committed',
        updated_at: new Date().toISOString(),
      });
      try {
        if (opts._failAt === 'before_import') throw new Error('injected failure before import');
        await projectCanonicalFile(
          engine,
          filePath,
          normalizedSlug,
          sourceId,
          digest,
          opts.noEmbed ?? false,
        );
        writeReceipt(receiptPath, {
          ...base,
          state: 'projected',
          updated_at: new Date().toISOString(),
        });
        return {
          status: currentDigest === digest ? 'noop' : 'projected',
          source_id: sourceId,
          slug: normalizedSlug,
          digest,
          path: filePath,
          receipt_path: receiptPath,
        };
      } catch (error) {
        const message = error instanceof Error ? error.message : String(error);
        writeReceipt(receiptPath, {
          ...base,
          state: 'projection_failed',
          updated_at: new Date().toISOString(),
          error_code: 'projection_failed',
        });
        return {
          status: 'file_only',
          source_id: sourceId,
          slug: normalizedSlug,
          digest,
          path: filePath,
          receipt_path: receiptPath,
          error: message,
        };
      }
    }, { ttlMinutes: PATH_LEASE_MINUTES }),
  );
}

export async function reconcileGeneratedOutputs(
  engine: BrainEngine,
  opts: ReconcileGeneratedOutputOpts = {},
): Promise<{ scanned: number; repaired: number; failed: number }> {
  const sourceId = opts.sourceId ?? 'default';
  const root = await resolveSourceRoot(engine, sourceId, opts.brainDir);
  const dir = receiptDirectory(root, opts.receiptDir);
  if (!existsSync(dir)) return { scanned: 0, repaired: 0, failed: 0 };

  let scanned = 0;
  let repaired = 0;
  let failed = 0;
  for (const name of readdirSync(dir).filter((entry) => entry.endsWith('.json')).sort()) {
    let receipt: GeneratedOutputReceipt;
    try {
      receipt = JSON.parse(readFileSync(join(dir, name), 'utf8')) as GeneratedOutputReceipt;
    } catch {
      failed++;
      continue;
    }
    if (receipt.version !== RECEIPT_VERSION || receipt.source_id !== sourceId) continue;
    if (receipt.state === 'projected') continue;
    scanned++;
    const filePath = join(root, receipt.relative_path);
    if (!isWriteTargetContained(filePath, root) || readGeneratedOutputDigest(filePath) !== receipt.digest) {
      failed++;
      continue;
    }
    const content = readFileSync(filePath, 'utf8');
    const result = await writeGeneratedOutput(engine, receipt.slug, content, {
      sourceId,
      brainDir: root,
      expectedDigest: receipt.digest,
      noEmbed: opts.noEmbed,
      receiptDir: opts.receiptDir,
    });
    if (result.status === 'projected' || result.status === 'noop') repaired++;
    else failed++;
  }
  return { scanned, repaired, failed };
}
